export const Property_Dict = {
  敏捷: "agility",
  力量: "strength",
  本能: "instinct",
  知识: "knowledge",
  风度: "presence",
  灵巧: "finesse",
  生命: "health",
  生命上限: "health_max",
  压力: "stress",
  压力上限: "stress_max",
  希望: "hope",
  希望上限: "hope_max",
  护甲: "armor",
  护甲上限: "armor_max",
  闪避: "evasion",
  重伤阈值: "major",
  严重阈值: "severe",
};
